name: manage-azure-policy-5e262f7e
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Kubernetes_clusters_should_be_accessible_only_over_HTTPS_1a5b4dca-0b6f-4cf5-907c-56316bc1bf3d/**'
#      - .github/workflows/manage-azure-policy-5e262f7e.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_5e262f7e}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Kubernetes_clusters_should_be_accessible_only_over_HTTPS_1a5b4dca-0b6f-4cf5-907c-56316bc1bf3d/**
